version: '3.9'

services:
  java_app:
    container_name: java_app
    image: img-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - .env.db